language: node_js
node_js:
  - stable
  - "12"
  - "10"
script: npm run lint && npm t
matrix:
  include:
    os: windows
    cache: false
    node_js: node
    script: git config --global core.autocrlf input && npm t
